name: Internal Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to Production
        run: |
          cd /root/var/www/qraynix.com
          git pull origin main
          npm install --production
          npm run build
          pm2 reload qraynix